### ISSUE TITLE
const in req and res serializers

### ISSUE THREAD

**Issue by KITSSamWaters** [pinojs/pino-std-serializers#11]
Hello,

Both the req and res serializers have a const keyword in them, which is not ES5 compatible - could these be changed to var?

req.js - `const _req = Object.create(pinoReqProto)`
res.js - `const _res = Object.create(pinoResProto)`

Thanks

**Comment by mcollina** [comment]
Why? We target a specific Node.js version, and const is supported there.

**Comment by davidmarkclements** [comment]
perhaps we should start using the `engine` flag in `package.json` across ecosystem modules to clarify our position (e.g. pino modules won't install for unsupported node versions)

**Comment by KITSSamWaters** [comment]
We're using lerna, which moves the modules it can to the project root (even though the server bundle, which is run through node 8) is not related to the web bundle.
Webpack then picks it up and includes it but, due to it being in node_modules, doesn't transpile it through babel - which means it doesn't get ES5ified

**Comment by mcollina** [comment]
I’m still lost. When does this error on Node.js?

**Comment by jsumners** [comment]
I need a [Babel fish](https://en.wikipedia.org/wiki/List_of_races_and_species_in_The_Hitchhiker%27s_Guide_to_the_Galaxy#Babel_fish) just to understand that. What I do understand, though, is that this isn't a Pino problem.

**Comment by davidmarkclements** [comment]
@KITSamWaters - am I correct in thinking
you're bundling for the browser? If so pino-std-serializers shouldn't be in the bundle - it's for the server side only. If you're requiring pino it should only be loading browser pino (which is the browser.js file in the main pino repo).

**Comment by davidmarkclements** [comment]
I think on principle - the solution here is to not have a process that
bundles server modules for the client with a hard es5 requirement. That
strategy is going to become untenable for you to progress with anyway

**Comment by jsumners** [comment]
It does look like there is a mishmash of `var` and `const` in this codebase. Personally, I would prefer the `var`s be converted to `const`s where appropriate.
