### ISSUE TITLE
Broken Stub Typing Package 

### ISSUE THREAD

**Issue by RyanThomas73** [pinojs/pino-std-serializers#119]
There appears to be a new version of `@types/pino-std-serializers` (version `4.0.0`) published to npm 16 days ago which is missing a type definition file and thus has broken our use of typescript. Not having the type definition file results in a TS2688 error being thrown  by the typescript compiler.

Npm reference:
https://www.npmjs.com/package/@types/pino-std-serializers

Part of the problem is the package `@types/pino@6.3.11` has a wildcard version reference to the @types/pino-std-serializers package
```
"@types/pino-std-serializers": "*"
```

To fix dependency chains broken by this, at a minimum, a new 4.0.1 version of @types/pino-std-serializers with a valid `index.d.ts` should be published.

**Comment by kibertoad** [comment]
Better solution would be publishing pino types without a wildcard type dependency

**Comment by RyanThomas73** [comment]
Yes but that would only fix the problem for packages that update to the new published pino types.

My understanding from looking at the repos is that the latest pino library major version (8) now contains the typings in the library itself and the published @types libraries are for people using older versions of pino.

Not publishing a new 4.0.1 version will cause all such references to remain broken.

**Comment by kibertoad** [comment]
pino-std-serializers include their own types as well, and this is the way going forward. otherwise we'll have to support types in two places

**Comment by RyanThomas73** [comment]
Yeah for new versions there shouldn't be any need to continue putting out the @types package.

We just need a new @types/pino-std-serializers 4.0.1 version to fix consumers that are auto picking up the 4.0.0 version and ideally new minor version of the existing @types/pino versions that no longer have the version wildcards

**Comment by mcollina** [comment]
I think you can send a PR to Definitelytyped to fix

**Comment by RyanThomas73** [comment]
> I think you can send a PR to DefinitelyTyped to fix

The types have been removed from definitely typed since they're not needed anymore in the new versions.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62975/files

Not sure, but guessing definitely typed automatically puts out the stub version when they're removed like this?
Definitely don't want to have to maintain them in 2 places even just for a while to fix this but also think it's important to try and and put a fix out for consumers that can't control when version values can be updated.

Maybe we could ping the definitely typed team and ask them about putting out a 4.0.1 version by hand just to fix the broken consumers?

**Comment by RyanThomas73** [comment]
Seems like there is an open issue at DefinitelyTyped with this problem occurring for multiple packages.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62793

Apparently the definitely typed tooling automatically includes the version wildcard `*` when there was an implicit typing dependency.

i.e.
@types/pino@6.x depended on @types/pino-pretty and @types/pino-std-serializers without explicitly declaring them in the /DefinitelyTyped/types/pino/package.json file. Thus the DefinitelyTyped tooling automatically * wildcards them.

Since the @types/pino package has been removed the following would be needed.
1. Temporarily re-add the typing to DefinitelyTyped with a correct package.json and explicit dependency versions
2. Wait for DefinitelyTyped to output a new @types/pino@6.3.13 version that does not have the wildcards
3. Remove the temporary typing 

Example PR for a different set of typing packages with the same problem
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63097/files

**Comment by jacoscaz** [comment]
Adding `@types/pino-std-serializers@2.4.0` as an explicit dependency to our project seems to work around this issue.

**Comment by richardtappenden** [comment]
Following...

**Comment by mcollina** [comment]
Closing as its something outside of the scope of this org.
