### ISSUE TITLE
Excluding request headers?

### ISSUE THREAD

**Issue by phillipj** [pinojs/pino-std-serializers#12]
Trying out pino these days, and it works like a charm 👍 

Any thoughts on excluding certain HTTP headers from the request? I would really like to avoid dumping end-user's `authorization` header w/JWT into our logs.

Previously I've been using [bunyan-middleware](https://github.com/tellnes/bunyan-middleware#options)'s `obscureHeader` option to accomplish this with bunyan. At first glance it doesn't look like there's something similar in these pino serialisers.

Have you accomplished something like this before or is it a plausible new feature of the standard request serialiser?

**Comment by jsumners** [comment]
Currently there is `pino-noir` that solves this. But pino@5 significantly improves this situation. We will hopefully get that out by year end or early next calendar year.

**Comment by phillipj** [comment]
Aha, thanks! My english was obviously lacking, "redaction" wasn't in my vocabulary until now.

Redaction is even documented on the pino website: http://getpino.io/#/docs/howtos?id=how-do-i-redact-sensitive-information
