### ISSUE TITLE
Check err object to be null

### ISSUE THREAD

**Issue by rehangit** [pinojs/pino-std-serializers#13]
Our logger ends up falling apart here as the object being serialized is null. Although this can be fixed at source but it should be possible to pass a null object. The serializer should handle the null object gracefully.

https://github.com/pinojs/pino-std-serializers/blob/ddb1fb9edad092c5495b3c08e026ccc37c143352/lib/err.js#L7

**Comment by mcollina** [comment]
Fixed by #15.
