### ISSUE TITLE
req serializer: add path prop that has url without qs

### ISSUE THREAD

**Issue by naseemkullah** [pinojs/pino-std-serializers#131]
I'm mostly using express these days, and i notice `req.url` contains the qs (because `req.originalUrl` does), not sure what behaviour is with fastify or other libs.

that said, would a PR be accepted to add a `req.path` prop (at least for express, so this would be done in the "[if `originalUrl` is truthy](https://github.com/pinojs/pino-std-serializers/blob/986ef19e19b9d68c2e821d948f066362a4f82311/lib/req.js#L71-L74)" branch) that with something like `req.originalUrl.split("?").shift()` ?

My use case is wanting to add the value of these as a tag/label in log based metrics and it should have a low cardinality, though I think it might make sense to have this in the standard req serializer.

**Comment by mcollina** [comment]
I would not add this kind of unneeded processing by default, I'd recommend you to override the default serializer.

**Comment by naseemkullah** [comment]
Ok makes sense, thanks

**Comment by naseemkullah** [comment]
Actually, I just realized we can use `req.baseUrl + req.path` for express to get the url without query params, would this be accepted as it doesn't involve any processing?

**Comment by jsumners** [comment]
This package is not tied to any specific frameworks. The provided wrapper utilities exist to support these kinds of scenarios.

**Comment by naseemkullah** [comment]
> This package is not tied to any specific frameworks.

While it isn't tied per se,[ it does adapt accordingly](https://github.com/pinojs/pino-std-serializers/blob/986ef19e19b9d68c2e821d948f066362a4f82311/lib/req.js#L71-L78).

>  The provided wrapper utilities exist to support these kinds of scenarios.

 Why the choice to check for `req.originalUrl` instead of tell express users to use the wrapper utility?

**Comment by naseemkullah** [comment]
Hmm in any case looks like any params in something like `foo/:id` are always templated so that would have to be addressed for my low cardinality use case, closing... for now ;)
