### ISSUE TITLE
Performance gains by using class, instead of Object.create(pinoResProto)

### ISSUE THREAD

**Issue by gerardo-lima-moonfare** [pinojs/pino-std-serializers#147]
hey, folks, first of all, thank you for your great work! 💪🏽 

I used code copied from [res.js](https://github.com/pinojs/pino-std-serializers/blob/master/lib/res.js) to create a performance test to compare creating new instances of `resSerializer` using the current syntax, based on `Object.create(myProto)`, to using `new MyClass`. According to this test, speed of `Object.create(myProto)` is about 37% slower than `new MyClass`.

As pino-std-serializers is used in http-pino (and its variants), I think this improvement on logs could be positive to many HTTP services.

Would you be interested into a PR to refactor these _constructor calls_? As this should not change behaviour, the existing tests should guarantee compatibility ... on a long shot, maybe you'd also be interested into porting this codebase to TypeScript?

Performance tests are here: https://jsperf.app/wajexuw/2

**Comment by jsumners** [comment]
> on a long shot, maybe you'd also be interested into porting this codebase to TypeScript?

No thank you.

> Performance tests are here: [jsperf.app/wajexuw/2](https://jsperf.app/wajexuw/2)

How are these tests representative of the Node.js versions we support?

**Comment by jsumners** [comment]
The engines field is ignored by package managers. We do not use it. Our supported runtimes are defined in our CI configuration. The matrix you chose is sufficient. 

My opinion on converting the code is covered in https://jrfom.com/posts/2023/10/31/js-classes/. In short, not worth it. 

@mcollina may have a different opinion.

**Comment by mcollina** [comment]
Based on your code, it seems that _lower is better_, and therefore `tPro` outperforms `tCla` everywhere. Am I reading this wrong?

**Comment by mcollina** [comment]
Thanks for your analysis, this was quite good. I think we can close this, as we will keep the code as-is.
