### ISSUE TITLE
reqSerializer creates a shallow copy of the request object

### ISSUE THREAD

**Issue by ghermeto** [pinojs/pino-std-serializers#19]
I'm building a custom serializer to sanitize some headers before logging and I had the impression that the parameter provider to the custom serializer was a deep serialized copy of the request, as the README reads: "the newly serialized request object".

However, on line [63 of lib/req.js](https://github.com/pinojs/pino-std-serializers/blob/master/lib/req.js#L63) `_req.headers` is given a reference to the request headers object.

I'm not sure if you want to make a copy of the `headers` object, but maybe you want to update the README.

For context, I can't use `redact` feature from `pino` because we let users provide their own pino logger instance and AFAIK child logger can't set `redact`...

**Comment by jsumners** [comment]
I'd say that if you want to take the performance hit for a deep clone you can do it as the first line of your custom serializer. Is that okay?

**Comment by ghermeto** [comment]
after running some benchmarks I ended up with something like this:
```js
function sanitizedRequestSerializer(req) {
    req.headers = Object.keys(req.headers).reduce((acc, key) => {
        if (!key.startsWith('secret_sauce_')) {
            acc[key] = req.headers[key];
        }
        return acc;
    }, {});
    return req;
}
```
deep cloning is not an option because of the performance hit... 

It wasn't clear to me, from the documentation alone, that was a shallow copy. Maybe that should be reflected in the README?

**Comment by jsumners** [comment]
Sure, we welcome any PR that improves documentation.

**Comment by ghermeto** [comment]
awesome, will do!
