### ISSUE TITLE
Request Serializer is still referencing a deprecated request property

### ISSUE THREAD

**Issue by al-bglhk** [pinojs/pino-std-serializers#43]
[This function](https://github.com/pinojs/pino-std-serializers/blob/d9989bba17f8fc225802aa826ea46df95ae329b6/lib/req.js#L57) causes fastify/light-my-request to emit warnings for deprecation whenever `request.connection` is accessed.

Refs:
https://github.com/fastify/light-my-request/blob/c677df30b7b5fa931422ba39c91ed25757390458/lib/request.js#L87
https://github.com/fastify/fastify/blob/5e0e674823642d851fefb73d78fc590325c880b2/lib/request.js#L134

Can I create a PR so that it will take from `request.socket` before `request.connection`?

**Comment by al-bglhk** [comment]
PR -  https://github.com/pinojs/pino-std-serializers/pull/44/files

**Comment by mcollina** [comment]
Thanks for the PR! What version of fastify are you using?

**Comment by al-bglhk** [comment]
I am using the latest fastify as of this writing (v3.9.2)

**Comment by al-bglhk** [comment]
I have updated the PR with fixed test cases. Please check https://github.com/pinojs/pino-std-serializers/pull/46

**Comment by francisdb** [comment]
I guess this can be closed since #46 is closed?
