### ISSUE TITLE
id is a string - causes failing pino tests upon integration

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino-std-serializers#6]
because the readme said "id defaults to an empty string" I made it default to empty string

but this now causes failing tests when integrating with pino (it's not expecting an ID to there)

I don't think we should include an id with empty string in output 

can we change the readme to id defaults to undefined, make id undefined, then release a major
(because technically prior pub was a patch, now this is api breaking,  so major)

**Comment by jsumners** [comment]
I'm not sure why it said "id defaults to an empty string". I must've been thinking about something else. I think making the readme match the code is more appropriate than making the code match the readme.
