### ISSUE TITLE
Hapi v17 – Connection Info

### ISSUE THREAD

**Issue by felixheck** [pinojs/pino-std-serializers#8]
Hi there!

Seems that switching to this module leads to bugs in hapi v17.
So does `request.connection` not exist, it's now `request.info` because multiple connection support was removed.

Unfortunately no time to fire a PR with tests etc.
Hope someone can tackle it :) 

Thanks

**Comment by mcollina** [comment]
Thanks for reporting! Can you provide a repro? It’d help immensely as hapi-pino tests are currently passing.

**Comment by felixheck** [comment]
There aren't any `remoteAddr` or `remotePort` tests :) 
Can push a repro after updating all the other plugins 👍

**Comment by mcollina** [comment]
thanks!


Il giorno mar 29 mag 2018 alle ore 14:40 Felix Heck <
notifications@github.com> ha scritto:

**Comment by felixheck** [comment]
You're welcome. Glad to contribute to the pino ecosystem
