### ISSUE TITLE
Restify req.url broken by #29

### ISSUE THREAD

**Issue by rektide** [pinojs/pino-std-serializers#88]
Hi, apologies,

In #29, `req.path` was made preferred to `req.url`, for finding the url. In restify however [req.path is a fucntion](https://github.com/restify/node-restify/blob/5c7eb95319aa54ef3b4b60d000d434824a666e18/lib/request.js#L357) (this link is to current master branch). This causes the url not to be logged for restify systems.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by rektide** [comment]
Working on it, sure. I plan on testing `req.path` if present to see if it's a function. This feels like it'll have the highest compatibility, at the cost of some speed. Other implementation suggestions welcome.
